[package]
name = "input-test"
description = "A GTK4 application that reports the keyboard and mouse input it receives, for testing wgaf's input synthesis."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
report = { workspace = true }
gtk4 = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
