#!/usr/bin/env bash
#
# Orchestrates building distribution packages for wgaf.
# Delegates to separate scripts for each distro package format.
#
# Usage:
#   bash scripts/package.sh           build everything this machine can
#   bash scripts/package.sh --deb     Debian, Ubuntu, Pop!_OS, Mint
#   bash scripts/package.sh --rpm     Fedora, RHEL, openSUSE
#   bash scripts/package.sh --arch    Arch, Manjaro, EndeavourOS (PKGBUILD)
#   bash scripts/package.sh --tar     everything else, including NixOS and Gentoo
#
# A missing packaging tool is reported and skipped, not treated as a failure.
# No distribution ships all four, so building the full set means building on
# more than one machine — or accepting that whoever runs this gets the formats
# their machine can make.
#
#   .deb   needs dpkg-deb   (Debian/Ubuntu have it; elsewhere: install dpkg)
#   .rpm   needs rpmbuild   (Fedora/openSUSE have it; Debian: apt install rpm)
#   Arch   needs makepkg    (Arch only; elsewhere a PKGBUILD is written for
#                            someone on Arch to build, which is what the AUR
#                            distributes anyway)
#   .tar.gz needs nothing, and is the fallback for any distribution without a
#          package of its own.
#
# WHAT A PACKAGE INSTALLS, AND WHAT IT DELIBERATELY DOES NOT
#
# System-wide: the two programs, the GNOME Shell extension, the systemd user
# service, the udev rule that makes typing possible, and the manual pages.
#
# Per-user: `config.toml` and `permissions.toml` into ~/.config/wgaf/ at mode
# 600, for whoever ran the install — **and only when they are not already
# there.** An upgrade never touches configuration you have edited. That matters
# most for permissions.toml: the shipped copy allows every capability, so
# overwriting it would silently turn a `Deny` you wrote back into `Allow`.
#
# It does not enable the extension for anyone, and does not add anyone to the
# `input` group. Both are per-user choices that need a logout anyway, so the
# package prints them rather than doing half of it.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
REPO_ROOT="$(pwd)"

SCRIPTS_DIR="$REPO_ROOT/scripts"
UUID="wgaf@wgaf.dev"
VERSION="$(sed -n 's/^version = "\([^"]*\)".*/\1/p' Cargo.toml | head -1)"
DIST="$REPO_ROOT/dist"
STAGE="$REPO_ROOT/target/package-root"

WANT_DEB=0
WANT_RPM=0
WANT_ARCH=0
WANT_TAR=0
case "${1:-}" in
    --deb)  WANT_DEB=1 ;;
    --rpm)  WANT_RPM=1 ;;
    --arch) WANT_ARCH=1 ;;
    --tar)  WANT_TAR=1 ;;
    "")     WANT_DEB=1; WANT_RPM=1; WANT_ARCH=1; WANT_TAR=1 ;;
    *) echo "unknown option: $1 (expected --deb, --rpm, --arch or --tar)" >&2; exit 2 ;;
esac

if [ -t 1 ]; then
    C_OK=$'\033[32m'; C_WARN=$'\033[33m'; C_DIM=$'\033[2m'; C_OFF=$'\033[0m'
else
    C_OK=""; C_WARN=""; C_DIM=""; C_OFF=""
fi
step() { printf '\n%s==>%s %s\n' "$C_DIM" "$C_OFF" "$1"; }
ok()   { printf '%s  ok%s  %s\n' "$C_OK" "$C_OFF" "$1"; }
skip() { printf '%sskip%s  %s\n' "$C_WARN" "$C_OFF" "$1"; }

[ -n "$VERSION" ] || { echo "could not read the version from Cargo.toml" >&2; exit 1; }

# --- build and stage --------------------------------------------------------

step "Building wgaf $VERSION"

# The same check `make build` makes, kept here because this script is run
# straight from a checkout and the linker error on its own is unhelpful.
printf 'int main(void){return 0;}' | cc -x c - -o /dev/null -lxkbcommon 2>/dev/null || {
    echo "libxkbcommon development files are missing — see 'make build'." >&2
    exit 1
}

cargo build --release --workspace
ok "wgaf and wgaf-daemon"

# The extension is packed with GNOME's own tool so the bundle is exactly what
# `make -C extension install` would produce — including the compiled settings
# schema, which a plain directory copy would leave out and which the emergency
# key needs.
make -C extension pack >/dev/null
ok "GNOME Shell extension"

# Manual pages are generated by a test, which is how the CLI's own definitions
# stay the single source for them.
#
# Cleared first, because the generator writes into this directory without
# emptying it and a removed command leaves its page behind. The first .deb
# built by this script shipped `wgaf-window-workspaces.1` — a command deleted
# two releases earlier — and a package documenting commands that do not exist
# is worse than one documenting none.
rm -rf target/man
cargo test -p wgaf-cli generate_man_pages -- --ignored >/dev/null 2>&1 || true
ok "manual pages ($(ls target/man 2>/dev/null | wc -l) pages)"

step "Assembling the file tree"

rm -rf "$STAGE"
install -d "$STAGE/usr/bin"
install -d "$STAGE/usr/share/gnome-shell/extensions/$UUID"
install -d "$STAGE/usr/lib/systemd/user"
install -d "$STAGE/usr/lib/udev/rules.d"
install -d "$STAGE/usr/share/doc/wgaf"
install -d "$STAGE/usr/share/man/man1"

install -m 755 target/release/wgaf "$STAGE/usr/bin/wgaf"
install -m 755 target/release/wgaf-daemon "$STAGE/usr/bin/wgaf-daemon"

unzip -qo "extension/$UUID.shell-extension.zip" \
    -d "$STAGE/usr/share/gnome-shell/extensions/$UUID"

# The bundle carries the schema as XML; GNOME reads the compiled form, and the
# emergency key's shortcut is stored in it. `gnome-extensions install` compiles
# it on the way into a user's home, which is why the hand-installed copy works —
# a package installing straight into /usr/share has to do it itself, and the
# first .deb this script built did not. Without it the extension loads and the
# kill-switch shortcut silently does nothing.
glib-compile-schemas "$STAGE/usr/share/gnome-shell/extensions/$UUID/schemas"
[ -f "$STAGE/usr/share/gnome-shell/extensions/$UUID/schemas/gschemas.compiled" ] ||
    { echo "the settings schema did not compile" >&2; exit 1; }

# The packaged unit runs the system-wide binary, where the repository's own
# copy points at a Cargo install under the user's home. Rewritten rather than
# kept in two files, so there is one unit to change when the unit changes.
sed 's|^ExecStart=.*|ExecStart=/usr/bin/wgaf-daemon|' \
    packaging/systemd/wgaf-daemon.service \
    > "$STAGE/usr/lib/systemd/user/wgaf-daemon.service"
chmod 644 "$STAGE/usr/lib/systemd/user/wgaf-daemon.service"

# Without this, wgaf can manage windows and cannot type or click. It is the one
# part of installation that genuinely needs root, which is exactly what a
# package is for.
cat > "$STAGE/usr/lib/udev/rules.d/99-wgaf-uinput.rules" <<'RULE'
# Lets members of the "input" group use /dev/uinput, which is how wgaf
# synthesizes keystrokes and pointer movement. Add yourself with:
#     sudo usermod -aG input $USER
# then log out and back in.
KERNEL=="uinput", GROUP="input", MODE="0660"
RULE
chmod 644 "$STAGE/usr/lib/udev/rules.d/99-wgaf-uinput.rules"

# Default configuration files — copied to ~/.config/wgaf/ during install
install -m 644 packaging/config.toml "$STAGE/usr/share/doc/wgaf/config.toml"
install -m 644 packaging/permissions.toml "$STAGE/usr/share/doc/wgaf/permissions.toml"
install -m 644 README.md CHANGELOG.md LICENSE "$STAGE/usr/share/doc/wgaf/" 2>/dev/null || true

if compgen -G "target/man/*.1" > /dev/null; then
    for page in target/man/*.1; do
        gzip -9nc "$page" > "$STAGE/usr/share/man/man1/$(basename "$page").gz"
        chmod 644 "$STAGE/usr/share/man/man1/$(basename "$page").gz"
    done
fi

ok "staged in $STAGE"
mkdir -p "$DIST"

# --- call distro-specific builders -------------------------------------------

[ "$WANT_DEB" = "1" ] && bash "$SCRIPTS_DIR/package-deb.sh"
[ "$WANT_RPM" = "1" ] && bash "$SCRIPTS_DIR/package-rpm.sh"
[ "$WANT_ARCH" = "1" ] && bash "$SCRIPTS_DIR/package-arch.sh"
[ "$WANT_TAR" = "1" ] && bash "$SCRIPTS_DIR/package-tar.sh"

# --- summary -----------------------------------------------------------------

step "Done"
ls -lh "$DIST" 2>/dev/null | tail -n +2 | awk '{print "      " $9 "  " $5}'

cat <<EOF

Try one before publishing it — that is the point of building locally:

    sudo apt install ./dist/wgaf_${VERSION}_$(dpkg --print-architecture 2>/dev/null || echo amd64).deb
    wgaf --version

Publish to the GitHub release for this version:

    gh release create v$VERSION dist/* --title "wgaf $VERSION" --notes-file CHANGELOG.md
    # or, if the release already exists:
    gh release upload v$VERSION dist/*
EOF

